/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rinkalinija;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author RK00448
 */
public class MyJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyJFrame
     */
    public MyJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDraw = new javax.swing.JButton();
        canvasPanel = new javax.swing.JPanel();
        tfXc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfYc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfRx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfRy = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        btnDraw.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 14)); // NOI18N
        btnDraw.setText("Draw");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });

        canvasPanel.setBackground(new java.awt.Color(255, 255, 255));
        canvasPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasPanelMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                canvasPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout(canvasPanel);
        canvasPanel.setLayout(canvasPanelLayout);
        canvasPanelLayout.setHorizontalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        canvasPanelLayout.setVerticalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Xc:");

        jLabel2.setText("Yc:");

        jLabel3.setText("Rx:");

        jLabel4.setText("Ry:");

        logArea.setColumns(20);
        logArea.setRows(5);
        jScrollPane1.setViewportView(logArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfYc, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfXc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRx))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRy))
                            .addComponent(btnDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(193, 193, 193))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfXc)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfYc)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRx)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRy)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDraw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                    .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        // TODO add your handling code here:
        // get user input     
        int xc=Integer.parseInt(tfXc.getText());
        int yc=Integer.parseInt(tfYc.getText());
        int rx=Integer.parseInt(tfRx.getText());
        int ry=Integer.parseInt(tfRy.getText());
               
        drawElipse(xc,yc,rx,ry);
    }//GEN-LAST:event_btnDrawActionPerformed

    private void drawElipse(int xc,int yc, int rx,int ry){
        Graphics g= canvasPanel.getGraphics();
        
        int ry2,rx2,i,xn,yn;
        float pn;
        
        
        
        i=0;
        xn=0;       // шаг
        yn=ry;      
        ry2=ry*ry;  // типа в квадрате
        rx2=rx*rx;  
        pn=(float)(ry2-rx2*ry+.25*rx2);
        
        // DEBUG 1
        g.setColor(Color.GREEN);
        g.drawLine(xc,yc,xn+xc,ry+yc);
        
        while((ry2*xn)<=(rx2*yn)){ // TODO что собой представляет?
            xn++;
            if(pn<0){
                // zem punkta
//                xn++;
                pn=pn+2*ry2*xn+ry2;
            }else{
//                xn++;
                yn--;
                pn=pn+2*ry2*xn+ry2-2*rx2*yn;
            }
            g.setColor(Color.RED);
            g.drawLine(xn+xc, yn+yc, xn+xc, yn+yc);
            g.setColor(Color.GRAY);
            drawSymmetric(xn,yn,xc,yc,g);
            logArea.append(String.format("1. Part %d.)\txn: %d yn:%d pn: %f\n",++i,xn,yn,pn));
        }
        //DEBUG 2
        g.setColor(Color.GREEN);
        g.drawLine(xc,yc,xn+xc,yn+yc);
        
        i=0; // reset counter
        pn=(float)(ry2*(xn+.5)*(xn+.5) 
                + rx2*(yn-1)*(yn-1) 
                - rx2*ry2);
        
        logArea.append("\n");
        
        while(yn>0){
            
            if(pn>0){
                yn--;
                pn=pn-2*rx2*yn+rx2;
            }else{
                yn--;
                xn++;
                pn=pn-2*rx2*yn+rx2+2*ry2*xn;
            }          
            g.setColor(Color.BLUE);
            g.drawLine(xn+xc, yn+yc, xn+xc, yn+yc);
            // draw other points
            g.setColor(Color.GRAY);
            drawSymmetric(xn,yn,xc,yc,g);
            logArea.append(String.format("2. Part %d.)\txn: %d yn:%d pn: %f\n",++i,xn,yn,pn));
        }
        //DEBUG
        g.setColor(Color.GREEN);
        g.drawLine(xc,yc,xn+xc,yn+yc);
    }
    
    private void canvasPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasPanelMouseClicked
        // TODO add your handling code here:
        sX1=evt.getX();
        sY1=evt.getY();
    }//GEN-LAST:event_canvasPanelMouseClicked

    private void canvasPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasPanelMouseReleased
        // TODO add your handling code here:
        sX2=evt.getX();
        sY2=evt.getY();
        
        int xc= (sX2+sX1)/2;
        int yc= (sY2+sY1)/2;
        int rx=Math.abs((sX2-sX1)/2);
        int ry=Math.abs((sY1-sY2)/2);
        drawElipse(xc,yc,rx,ry);
    }//GEN-LAST:event_canvasPanelMouseReleased
    
    /** Draws symmetrical points */
    private void drawSymmetric(int xn,int yn,int xc,int yc,Graphics g){
        // simetriski pret OY
        g.drawLine(xn+xc, -yn+yc, xn+xc, -yn+yc);
        // simetriski pret OX un OY
        g.drawLine(-xn+xc, -yn+yc, -xn+xc, -yn+yc);
        // simetriski pret OX
        g.drawLine(-xn+xc, yn+yc, -xn+xc, yn+yc);
    }
    
    private static int sX1,sY1,sX2,sY2;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDraw;
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logArea;
    private javax.swing.JTextField tfRx;
    private javax.swing.JTextField tfRy;
    private javax.swing.JTextField tfXc;
    private javax.swing.JTextField tfYc;
    // End of variables declaration//GEN-END:variables
}
